#!/bin/sh




case "$1" in
    start)

        for i in 0 1 2 3; do sudo ip link set can$i type can bitrate 500000; done

        ach  mk -1 -o 666 ref-torso
        ach  mk -1 -o 666 state-torso
        ach  mk -1 -o 666 ref-left
        ach  mk -1 -o 666 state-left
        ach  mk -1 -o 666 joystick
        ach  mk -1 -o 666 pir-ctrl
        ach  mk -1 -o 666 pir-state
        ;;
    *)
        echo "Invalid command"
        exit 1
        ;;
esac
