#!/bin/sh
#
# Copyright (c) 2013, Georgia Tech Research Corporation
# All rights reserved.
#
# Author(s): Neil T. Dantam <ntd@gatech.edu>
# Georgia Tech Humanoid Robotics Lab
# Under Direction of Prof. Mike Stilman <mstilman@cc.gatech.edu>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above
#       copyright notice, this list of conditions and the following
#       disclaimer.
#     * Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials
#       provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# ''AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
# OF THE POSSIBILITY OF SUCH DAMAGE.

if test -x ~/local/etc/init.d/sns; then
    SNS=~/local/etc/init.d/sns
elif test -x /usr/local/etc/init.d/sns; then
    SNS=/usr/local/etc/init.d/sns
elif test -x /etc/init.d/sns; then
    SNS=/etc/init.d/sns
else
    echo "Could not find SNS program"
    exit 1
fi

PIRANHA_HOST=calvin
PIRANHA_VISION_HOST=baley

case "$1" in
    start)
        $SNS run -d ach-pir-ctrl -- \
            achd -r push $PIRANHA_HOST pir-ctrl
        $SNS run -d ach-pir-state -- \
            achd -r pull $PIRANHA_HOST pir-state
        $SNS run -d ach-pir-complete -- \
            achd -r pull $PIRANHA_HOST pir-complete
        $SNS run -d ach-pir-config -- \
            achd -r pull $PIRANHA_HOST pir-config
        $SNS run -d ach-pir-marker -- \
            achd -r pull $PIRANHA_VISION_HOST pir-marker
        $SNS run -d ach-pir-marker-filt -- \
            achd -r pull $PIRANHA_VISION_HOST pir-marker-filt
        ;;
    stop)
        $SNS kill ach-pir-ctrl
        $SNS kill ach-pir-state
        $SNS kill ach-pir-complete
        $SNS kill ach-pir-config
        $SNS kill ach-pir-marker
        $SNS kill ach-pir-marker-filt
        ;;
    *)
        echo "Invalid command"
        exit 1
        ;;
esac
