#!/bin/sh




case "$1" in
    start)
        achcop -rd  -P /tmp/ach-pir-joy.ppd -p /tmp/ach-pir-joy.pid -- \
            achd -r push calvin joystick
        ~/local/etc/init.d/sns run -d -r  joyd -- joyd-logitech-f310
        ;;
    *)
        echo "Invalid command"
        exit 1
        ;;
esac
