#!/bin/sh
#
# Copyright (c) 2013, Georgia Tech Research Corporation
# All rights reserved.
#
# Author(s): Neil T. Dantam <ntd@gatech.edu>
# Georgia Tech Humanoid Robotics Lab
# Under Direction of Prof. Mike Stilman <mstilman@cc.gatech.edu>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above
#       copyright notice, this list of conditions and the following
#       disclaimer.
#     * Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials
#       provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# ''AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
# OF THE POSSIBILITY OF SUCH DAMAGE.

if test -x ~/local/etc/init.d/sns; then
    SNS=~/local/etc/init.d/sns
elif test -x /usr/local/etc/init.d/sns; then
    SNS=/usr/local/etc/init.d/sns
elif test -x /etc/init.d/sns; then
    SNS=/etc/init.d/sns
else
    echo "Could not find SNS program"
    exit 1
fi

pir_ach_mk() {

    ach mk -1 -o 666 ref-torso
    ach mk -1 -o 666 state-torso
    ach mk -1 -o 666 ref-left
    ach mk -1 -o 666 state-left
    ach mk -1 -o 666 ref-right
    ach mk -1 -o 666 state-right

    ach mk -1 -o 666 sdhref-left
    ach mk -1 -o 666 sdhstate-left

    ach mk -1 -o 666 sdhref-right
    ach mk -1 -o 666 sdhstate-right

    ach mk -1 -o 666 ft-left
    ach mk -1 -o 666 ft-right
    ach mk -1 -o 666 ft-bias-left
    ach mk -1 -o 666 ft-bias-right

    ach mk -1 -o 666 pir-ctrl
    ach mk -1 -o 666 pir-state

    ach mk -1 -o 666 joystick
}

pir_ach_rm() {
    ach rm ref-torso
    ach rm state-torso
    ach rm ref-left
    ach rm state-left
    ach rm ref-right
    ach rm state-right
    ach rm joystick
    ach rm pir-ctrl
    ach rm pir-state
    ach rm ft-left
    ach rm ft-right
    ach rm ft-bias-left
    ach rm ft-bias-right
}

CAN_L=can0
CAN_R=can1

CAN_SDH_L=can2

pir_start() {
    pir_ach_mk
    $SNS run -d -r lwa-left -- \
        can402 -f $CAN_L -R 1 -C 0 -n 3 -n 4 -n 5 -n 6 -n 7 -n 8 -n 9 -c ref-left -s state-left
    $SNS run -d -r lwa-right -- \
        can402 -f $CAN_R -R 1 -C 0 -n 3 -n 4 -n 5 -n 6 -n 7 -n 8 -n 9 -c ref-right -s state-right

    $SNS run -d -r ft-left -- \
        cftd -f $CAN_L -n 27 -c ft-left -b ft-bias-left -W 1e6
    $SNS run -d -r ft-right -- \
        cftd -f $CAN_R -n 27 -c ft-right -b ft-bias-right -W 1e6

    $SNS run -d -r sdh-left -- \
        sdhiod -b $CAN_SDH_L -c sdhref-left -s sdhstate-left
}

pir_stop() {
    $SNS kill lwa-left
    $SNS kill lwa-right
    $SNS kill ft-left
    $SNS kill ft-right
    $SNS kill sdh-left
}

case "$1" in
    start)
        pir_start
        ;;
    stop)
        pir_stop
        ;;
    *)
        echo "Invalid command"
        exit 1
        ;;
esac
