#!/bin/sh


snsplot pir-reg tf -0 -1 -1 1 -i 0 -i 1 -i 2 -i 3 -i 0 -t q-raw &
snsplot pir-reg tf -0 0 -1 1 -i 4 -i 5 -i 6 -t x-raw &
snsplot pir-reg tf -0 -1 -1 1 -i 7 -i 8 -i 9 -i 10 -t q-filt &
snsplot pir-reg tf -0 0 -1 1 -i 11 -i 12 -i 13 -t x-filt
